baseURL = 'https://jaimanp1.github.io/Website/'
languageCode = 'en-us'
title = "Homepage"
theme = 'papermod'

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3

enableGitInfo = true
[params]
  ShowReadingTime = false
  ShowPostNavLinks = false
  math = true          
  homeInfoParams = false
  mainSections = []
  ShowLastMod = true

relativeURLs = true
canonifyURLs = true

[taxonomies]
  tag = "tags"
  category = "categories"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
