baseURL = 'https://jaimanp1.github.io/Website/'
languageCode = 'en-us'
title = "Jaiman Parekh's Homepage"
theme = 'papermod'

[[menu.main]]
name = "Research"
url = "/research/"
weight = 3

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 4

[params]
  ShowReadingTime = false
  ShowPostNavLinks = false
  math = true          
  homeInfoParams = false
  mainSections = []

relativeURLs = true
canonifyURLs = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
