baseURL = 'https://jaimanp1.github.io/Website/'
languageCode = 'en-us'
title = "Jaiman Parekh's Homepage"
theme = 'PaperMod'
publishDir = "public"

[[menu.main]]
name = "Classes"
url = "/classes/"
weight = 2

[[menu.main]]
name = "Research"
url = "/research/"
weight = 3

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 4

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 5

[params]
  ShowReadingTime = false
  ShowPostNavLinks = false
  math = true          
  homeInfoParams = false
  mainSections = []

relativeURLs = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
